Repository eoscostarica/eos-rate, pull requests merged in 2018-11, with the labels that each got.

#69 feat(home): create home page
  src/components/video.js
  src/config/theme.js
  src/language/en.json
  src/language/es.json
  src/models/home.js
  src/models/index.js
  src/routes/home/cover.js
  src/routes/home/index.js
  src/routes/home/subTopic.js
  src/services/bps.js
Labels: front-end

#70 feat(compare): basic compare tool functionality
  package.json
  src/components/block-producer-card.js
  src/components/bock-producer-card/BlockProducerCard.js
  src/components/bock-producer-card/index.js
  src/components/compare-tool/compare-graph-view.js
  src/components/compare-tool/compare-slider-view.js
  src/components/compare-tool/index.js
  src/components/layout.js
  src/language/en.json
  src/language/es.json
  src/models/blockProducers.js
  src/routes/block-producers/index.js
  src/routes/settings/index.js
  src/store.js
Labels: front-end

#75 feat(footer): add footer with eoscostarica logo and share buttons
  public/eoscostarica-logo.png
  src/components/layout.js
  src/components/main-footer.js
Labels: DON'T MERGE

#91 fix(webapp): add rel="noopener noreferrer" to _blank anchors
  services/frontend/src/components/block-producer-card.js
Labels: security
